eureka:
  client:
    register-with-eureka: false
server:
  port: 8888
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id:  cities
          uri: http://localhost:8083
          predicates:
            - Path=api/villes/**
